### ISSUE TITLE
Help testing against edge resque

### ISSUE THREAD

**Issue by steveklabnik** [KensoDev/perform_later#11]
Hey there! 

I'm gearing up to work on Resque 2.0, and I'd like to coordinate better with plugin authors to make sure stuff doesn't break.

I'd like to know a few things:
1. Can I do something to help get you testing against edge Resque?
2. Are you monkey-patching anything in Resque currently? Can 2.0 expose an API to help you not have to do that any more?
3. Do you need any help in bringing your plugin up-to-date with the latest Resque?

Thanks!

Related: https://github.com/defunkt/resque/issues/880

**Comment by KensoDev** [comment]
Hi,

Sorry for the (VERY) late reply on this
1. No, I plan to do this over the upcoming days.
2. Yes, I am patching Resque for argument parsing: https://github.com/KensoDev/perform_later/blob/master/lib/resque_mailer_patch.rb, any type of argument parsing middleware will help to do this in a cleaner way.
3. No, I am good.

related: https://github.com/resque/resque/issues/880 (doing this since the original repo moved).

**Comment by steveklabnik** [comment]
No worries about how long this took! That's why issues are asynchronous.

I'll look into an argument parsing api to help out. If you have any suggestions, please let me know.

**Comment by KensoDev** [comment]
If you are open to inserting middleware for args parsing, I can certainly help out with that.

**Comment by steveklabnik** [comment]
I need to actually look at exactly what that means, but I'm open to all things. :) I haven't read your code yet.

**Comment by KensoDev** [comment]
Put simply, you just don't pass around the args as is.
This way, you can pass AR objects, and translate them back and forth.

for example.

``` ruby
user = User.find some_user_id
SomeClass.perform_later(user)
```

When passed into Redis, this does not get marshaled, it's rather "translated" into "AR:User:1", and then when the worker picks is up from the queue, it tries to find it in the database.

**Comment by steveklabnik** [comment]
Ahh, gotcha. Yes, I should have something for you.

**Comment by KensoDev** [comment]
Let me know if you need anything from me, I will definitely love to give you a hand with this.

**Comment by steveklabnik** [comment]
Word. Basically, 
1. I want to go back to JSON 'marshalling' and not the `Marshall` marshaling we had in master,
2. i don't see why, as part of the marshalling process, we can't have a few different 'processors' that process stuff before it hits Redis.

**Comment by KensoDev** [comment]
is this something that's already in place or planned for the future?

**Comment by steveklabnik** [comment]
It's something I just thought of while discussing this with you.

**Comment by KensoDev** [comment]
Ah, gotcha.
Again, let me know what I can do to help

**Comment by steveklabnik** [comment]
Totally. If you want to give a shot at adding either something like this or something that'll help you to resque, please send a pull request. I probably won't be trying this for a few weeks.

**Comment by KensoDev** [comment]
Added to my open source TODO's.
Making no promises, but I will try to make time for this soon.

**Comment by steveklabnik** [comment]
Totally. :+1:
